"""Initial tables

Revision ID: e4ce94579110
Revises: 
Create Date: 2025-12-07 02:07:01.387723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ce94579110'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=False),
    sa.Column('script', sa.Enum('LATIN', 'DEVANAGARI', 'ARABIC', 'BENGALI', 'CYRILLIC', 'CJK', 'OTHER', name='scripttype'), nullable=False),
    sa.Column('direction', sa.Enum('LTR', 'RTL', name='scriptdirection'), nullable=False),
    sa.Column('speakers', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', 'ANNOTATOR', 'REVIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('annotators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'TESTING', 'APPROVED', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='annotatorstatus'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=False),
    sa.Column('pending_earnings', sa.Float(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('available_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('preferred_task_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('annotation_type', sa.Enum('NER', 'SENTIMENT', 'CLASSIFICATION', 'TRANSLATION', 'TRANSCRIPTION', 'SPAN_LABELING', 'RELATION_EXTRACTION', 'QA', 'SUMMARIZATION', 'RLHF', name='annotationtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('guidelines_url', sa.String(length=500), nullable=True),
    sa.Column('label_config', sa.JSON(), nullable=True),
    sa.Column('price_per_task', sa.Float(), nullable=False),
    sa.Column('estimated_time_per_task', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('min_annotators_per_task', sa.Integer(), nullable=False),
    sa.Column('require_native_speakers', sa.Boolean(), nullable=False),
    sa.Column('min_annotator_rating', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_studio_project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('annotator_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('proficiency', sa.Enum('NATIVE', 'FLUENT', 'ADVANCED', 'INTERMEDIATE', name='proficiencylevel'), nullable=False),
    sa.Column('is_native', sa.Boolean(), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.Column('qualification_score', sa.Float(), nullable=True),
    sa.Column('tasks_in_language', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'IN_PROGRESS', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='taskstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('label_studio_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('annotator_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('label_studio_annotation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotations')
    op.drop_table('tasks')
    op.drop_table('language_skills')
    op.drop_table('projects')
    op.drop_table('annotators')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
